### ISSUE TITLE
Comparison with Reflexion

### ISSUE THREAD

**Issue by allanj** [FloridSleeves/LLMDebugger#1]
As the code is also based on Reflexion,  and I wonder how is it compared with the approach of Reflexion.

Understand that different version of OpenAI APi might behave differently, I wonder if you have done some analysis to compare that

**Comment by FloridSleeves** [comment]
Since our work is a *debugging* solution, not a program generator, LDB is orthogonal to program generator works like Reflexion, LCTS, etc. In the paper, we have the result based on Reflexion, as shown in Table 2. We use [data](https://github.com/noahshinn/reflexion/blob/main/programming_runs/root/reflexion_humaneval_py_pass_at_1/reflexion_humaneval_py_pass_at_1.jsonl) from the Reflexion repo.

**Comment by allanj** [comment]
Thanks, understand the concept you define. IMO, they seem to essentially share roughly the same goal (in terms of the task of HumanEval), to have a good program for the task. 

But appreciate the results given in the table. 

One final question: so are we using the test cases existing in the HumanEval dataset?

**Comment by FloridSleeves** [comment]
> One final question: so are we using the test cases existing in the HumanEval dataset?

Yes. The test cases are extracted from the docstrings.
